Homework 2
vessellook/2020-1-Atom-QA-Python-A-Vessellook pull request #2
Opened 2020-10-11 10:18 UTC by vessellook

# Домашнее задание № 2

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
* Написаны объекты главной страницы, страницы со списком кампаний, страницы создания кампании и страницы управления сегментами + соответствующие локаторы
* Написаны позитивный и негативный тесты на авторизацию
* Написан тест на создание кампании и её удаление
* Написан тест на создание сегмента и его удаление
* Попытка добавить к тестам подписи для allure
* Тесты можно запустать на селеноиде
* Тесты можно запускать в параллельном режиме. Тут вылезали ошибки, но они решались добавлением задержек куда только можно

В файле variables две переменные EMAIL и PASSWD должны относиться к существующему в системе аккаунту

2020-10-12 23:08 UTC, snicks92 requested changes
Отличная работа. Понравилось что написал много разных тестов, некоторые из них даже с параметризацией. Очень понравился способ заведения локаторов. Понравилось что все в аллюр степах и сразу видно что делает тест. Понравилось что подумал над параллельностью и генерацией уникальных имен. Понравилась архитектура проекта и как выполняются действия/проверки.

Что можно улучшить (по мелочи) отписался ниже в комментариях.

Отдельно сказал бы про аллюр, Оно конечно здорово, но если тестов станет больше, ты замучаешься в каждом тесте проставлять аллюр степы. Плюс они реально в каокй то момент начинают перегружать тестовый метод. Я посмотрел где и как ты из выставляешь, часть точно можно вынести из тела теста и декорировать нужные методы пейджей.

Например так. Параметр таким образом так же попадет в степ.

```python
@allure.step("create segment with name {segment_name}")
def create_segment(self, segment_name: str) -> None:
    ....
```

В остальном все просто отлично

2020-10-12 23:08 UTC, sniiick commented on hw2/code/tests/test_basic.py
> +# @pytest.mark.skip(reason="It's working fine")
давай сразу уберем много комментов в коде

2020-10-12 23:08 UTC, sniiick commented on hw2/code/conftest.py
> +                                       )
что то практически копипаста для хрома и фф, давай попробуем избавиться

2020-10-12 23:08 UTC, sniiick commented on hw2/code/tests/test_basic.py
> +@pytest.mark.parametrize('email, password', [('email-invalid', 'some-password')])
а для чего тут параметризация? раз уж сделал можно добавить параметров (например пустой логин или пустой пароль, admin|admin итд)

2020-10-12 23:08 UTC, sniiick commented on hw2/code/ui/pages/base_page.py
> +        return self.driver.title
не то чтобы придирка, но логичнее сделать через `@property`

2020-10-12 23:08 UTC, sniiick commented on hw2/code/ui/pages/create_campaign_page.py
> +        sleep(10)
а чего ждем? и почему 10? видел не только тут

2020-10-12 23:08 UTC, sniiick commented on hw2/code/ui/pages/create_campaign_page.py
> +        carousel.add_banner('test', os.path.abspath('../res/img.jpg'))
будет работать только если я запустился из папки code. чтобы сделать запуск универсальным из любой папки - можно определить полный путь до текущего файла через abspath(__file__), и далее вверх через parent дойти до реального местопоожения img.jpg

2020-10-12 23:09 UTC, snicks92 requested changes

2020-10-12 23:09 UTC, snicks92 commented on hw2/code/tests/test_basic.py
> +    with allure.step(f'create segment with name {segments_page}'):
create segment with name {segments_name}?

2020-10-13 04:39 UTC, vessellook commented on hw2/code/ui/pages/create_campaign_page.py
> +        sleep(10)
скрипт не успевает отработать либо страница не успевает прогрузиться, поэтому элемент не находится, тест крашился. Ну, я подбирал подходящую задержку таким образом

2020-10-13 05:51 UTC, vessellook commented
@snicks92 @SK1995 Код отрефакторил, постарался исправить все замечания. Прилагаю [коммент про time.sleep()](https://github.com/vessellook/2020-1-Atom-QA-Python-A-Vessellook/pull/2#discussion_r503662806)

2020-10-13 08:20 UTC, snicks92 approved these changes

2020-10-13 08:21 UTC, merged

2020-10-13 08:21 UTC, snicks92 commented
Не смотря на некоторые замечания (в основном стилистические) поставлю максимально 12, отличная работа, спасибо